# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 277b628a2f368b96ea0ef1efd4211517b7f2bafd4b42ddc7baead022569684006f93dab1b1876ae8d14ffae268ea064751d423b3e3ce308360d3005946b2af17

test:
  secret_key_base: 065446b422c2dcdfc870108715c5c353f76af1f432710f98e02eadb920b61e8135b9baecd1e162eb5641d87ab616ff205db911b6489bf121ab2ce515e9406e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
